const motivations = [
    'You suck.',
    'No one likes you.',
    'In the land of the witless you would be king.',
    'Your inferiority complex is fully justified.',
    'It is impossible to underestimate you.',
    'You remind me of a penny. Two-faced, not worth much.',
    "I'll never forget the time we met. But I'll keep trying.",
    'If I said anything to offend you, it was purely intentional.',
    "You look like something I'd draw with my left hand.",
    'If you have something to say, raise your hand and place it over your mouth.',
    "You're more disappointing than a raisin cookie.",
    "Yes, hold still. I'm trying to imagine you with personality.",
    "You're as useless as the 'ueue' in 'queue'.",
    "Some day you'll go far... and I hope you stay there.",
    'Your family tree must be a circle.',
    "You're a real Vice Admiral of the Narrow Seas, huh?",
    'You have the subtlety of a brick and the depth of a shot glass.',
    "Keep rolling your eyes. Maybe you'll find a brain back there.",
    'Go polish your Crocs.',
    "If I wanted to kill myself, I'd climb to your ego and jump to your IQ.",
    'You look like rejected Shrek concept art.',
    'Have you ever tried not being the way that you are?',
    'If laughter is the best medicine, your face must be curing the world.',
    "The best part about me, is I'm not you.",
    "They say people get what they deserve. In your case it's a participation trophy.",
    'You look like the "before" picture in a commercial for antidepressants.',
    'If you were the trophy at the end of my race, I would walk backwards.',
    'If your face was any oilier the US Army would try to liberate it.',
    'You are about one bit short of a byte.',
];